### ISSUE TITLE
Undefined mixin 'keyframes'

### ISSUE THREAD

**Issue by davidxcarroll** [Aweary/gradient-animation.scss#1]
Hi! I noticed you're referencing `keyframes` a mixin that doesn't appear to come from anywhere. Am I missing something?

**Comment by aweary** [comment]
🤷‍♂️ I haven't looked at this repo in a couple years, I'm not sure what I was doing. I think it's safe to say this is unmaintained and I don't intend to work on it in the future, sorry!
